### ISSUE TITLE
paasta remote run needs to support constraints

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#1087]
we need to be able to add constraints to the tasks to be run by remote run - specifically, ``LIKE`` ``UNLIKE`` ``EQUALS``. Then we can support ``deploy_whitelist``  & ``deploy_blacklist`` which are needed.

**Comment by EvanKrall** [comment]
Another option:

Instead of taking `deploy_whitelist` / `deploy_blacklist` and turning it into a Marathon/Chronos-like constraint language, and then parsing that, we could take an approach like in https://github.com/Yelp/paasta/pull/1069/files -- write functions `offer_matches_deploy_blacklist` and `offer_matches_deploy_whitelist`, and then check those in `start_task`.

Eventually, though, I think we'll want to implement MAX_PER constraints (at the very least, MAX_PER host, but we really should have MAX_PER habitat, etc.), and I don't know whether we'd want to describe those with the same language that Marathon uses, or add a configuration option for it.

**Comment by keymone** [comment]
there is a problem with implementing MAX_PER for AdhocScheduler, as that only runs single task but somebody could potentially launch multiple adhoc jobs - we can't communicate that across frameworks.

**Comment by keymone** [comment]
done in 1090
