### ISSUE TITLE
wait-for-deployment should be less picky

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1169]
Today a deploy was held up because wait-for-deployment took longer than necessary to exit, due to two problems:

 - Turns out my conditional in https://github.com/Yelp/paasta/pull/1141/files was wrong -- I think we want >, not <, so when you have e.g. 11/10 instances, wait-for-deployment will continue blocking. This can happen if marathon does marathon things, or if the autoscaler adjusts the desired number of instances down.
 - wait-for-deployment will block as long as the Marathon status is anything other than Running, so "Deploying" and "Waiting" will block. I think this is unnecessary -- if we have enough instances, we have enough instances.

We could also make wait-for-deployment aware of bounce_margin_factor, but to be honest we might just be able to get rid of any checking of replication, and rely on the bounce to do the right thing. (At least for crossover bounce -- by the time there are no more of the old instances, there should be enough new ones. This is not true for brutal or downthenup.)

**Comment by solarkennedy** [comment]
@somic this is a good optimization to the bounce if you are interested.

**Comment by somic** [comment]
@solarkennedy my PR above addressed one of the aspects of this issue (2nd point), you addressed the first point in another PR and what's left is this:

"
We could also make wait-for-deployment aware of bounce_margin_factor, but to be honest we might just be able to get rid of any checking of replication, and rely on the bounce to do the right thing. (At least for crossover bounce -- by the time there are no more of the old instances, there should be enough new ones. This is not true for brutal or downthenup.)
"

Drop this for now or reopen this issue in order to get this done?

**Comment by solarkennedy** [comment]
I'm ok with this being considered "done". You could argue that the margin factor is really for the bounce "in progress" and shouldn't be considered for "completion".
