### ISSUE TITLE
PORT exported by paasta makes it difficult to do dockerfiles according to best practices

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#152]
From https://docs.docker.com/v1.8/articles/dockerfile_best-practices/#cmd you should use the json syntax
From https://github.com/Yelp/dumb-init it should look like `CMD ["dumb-init", "...", "..."]`

Paasta runs `--env=PORT=This_service_is_listening_on_the_PORT_variable__You_must_use_8888__see_y/paasta_deploy`

Even if you do it correctly with a dockerfile that looks like this:

```dockerfile
...
WORKDIR /code

ENV     PATH=/code/virtualenv_run/bin:$PATH
ENV     BASEPATH=/code
ENV     PORT=8888

CMD     ["dumb-init", "python", "./serviceinit.d/www_pages start-no-daemon"]
```

The `--env` line clobbers my Dockerfile's *correct* setting.

A workaround (which kinda sucks): 
`["dumb-init" "sh" "-c" "export PORT=8888; exec python serviceinit.d/www_pages start-no-daemon"]`

Suggestion: remove `--env=PORT=...` for two reasons:
1. It's yelpy
2. It breaks best practices

**Comment by solarkennedy** [comment]
We have had this issue since the beginning due to Marathon's behavior. I agree your suggestions. PAASTA-1114 internal is the blocking ticket.

**Comment by EvanKrall** [comment]
Marathon overrides the PORT environment variable with the external port that it allocated you, even if PORT is set with `ENV` in your Dockerfile, or as an environment variable in the Marathon app definition. Unfortunately, a lot of our services will bind to `$PORT` if it's set, causing them to bind to some port between 31000 and 32000 inside the container, instead of 8888 as desired.

The `--env=PORT=...` in local-run is emulating Marathon's behavior, so we can intentionally trigger that behavior under local-run (where things are easier to debug) instead of it only happening once deployed.

As the internal tracking ticket mentions, once we have all our clusters on Marathon 10+, we can set --env_vars_prefix to make Marathon set e.g. `MARATHON_PORT` instead of `PORT`.
