### ISSUE TITLE
Deployd doesn't notice when autoscaling is enabled for a service?

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1604]
@gstarnberger enabled autoscaling on a service; the autoscaler started it at max_instances and then scaled down on the next run, but deployd never noticed that it should run setup_marathon_job. I assume this is because watchers are only initialized when deployd starts?

cc @mattmb @fboxwala

**Comment by mattmb** [comment]
I don't think we have an itest but it is designed to support this. Have a look at: https://github.com/Yelp/paasta/blob/master/paasta_tools/deployd/watchers.py#L43

The idea is that we start from the autoscaling root node and then recursively watch all the sub nodes. When new nodes appear they should also get watchers. I can't say that we know it to be bulletproof, I've seen at least one instance in the past where something wasn't being watched. Did you pull any logs?

**Comment by EvanKrall** [comment]
I can take a look at the logs again, but from what I remember, the deployd said nothing about the service in question.

I also didn't see any "[Adding watch on](https://github.com/Yelp/paasta/blob/master/paasta_tools/deployd/watchers.py#L65)" lines, either on Friday when this happened or on the day when deployd started last, but I assume that's because we have debug logging turned off.

**Comment by solarkennedy** [comment]
@fboxwala can you help confirm/deny if your recent watchers disabling change has inadvertently stopped zk watchers for deployd in prod?

**Comment by fboxwala** [comment]
My change _shouldn't_ have changed any behavior, unless someone started setting `disabled_watchers` in any configs. I'll double check my changes though. Does it seem like none of the watchers are being started?

**Comment by fboxwala** [comment]
My [unit test](https://github.com/Yelp/paasta/blob/master/tests/deployd/test_deployd_master.py#L441) is behaving as expected when the `disabled_watchers` list is empty, which is what I pass as the default.

**Comment by solarkennedy** [comment]
I can confirm this experimentally, here was my repro procedure:
1. use wchp to every zk server asking for watchers, confirm it is not there
2. Add autoscaling to a server (example_happyhour)
3. Watch deploy logs, notice the soa-config watcher trigger, sets to max instances (expected)
4. watch autoscaler logs, it sets a new zk node to scale down
5. Run wchp again, no watchers on the new service at all

I second @EvanKrall 's suspicion that it only gets watchers on startup. The watchers are *on* though, just not picking up new services.

Running wchp I only see watchers on "instances", non on the root folders. 

Is the bug not exactly here?
https://github.com/Yelp/paasta/blob/37d5179dfeb6171f3f3a6e13dd1dee6d27ce2e3f/paasta_tools/deployd/watchers.py#L58-L62

The logic is currently:
1. If we are in a services' folder with `instances`, watch it
2. Otherwise for each-watch each services's folder

We need a 3, where if we are at the root, we watch the root for new services. Right?

**Comment by solarkennedy** [comment]
@mattmb @chlgit  I think you fixed this right?

**Comment by chlgit** [comment]
Right, this has been fixed.
